version: '3.7'
services:
 diat-qa-db:
  image: mysql:5.7
  environment:
   MYSQL_ROOT_PASSWORD: Igss.2025
   MYSQL_DATABASE: diat_qa
   MYSQL_USER: usr_laravel
   MYSQL_PASSWORD: Usr.igss.2025
  ports:
   - 33089:3306
  volumes:
   - ./database/schemas/:/var/lib/mysql
  networks:
   diat_qa_net:
    ipv4_address: 174.25.100.25
 diat-qa:
  build:
   context: ./
   dockerfile: Dockerfile
  ports:
   - 9000:80
  volumes:
   - ./code-dev:/var/www
   - ./code-dev/public:/var/www/html
  networks:
   diat_qa_net:
    ipv4_address: 174.25.100.26
  depends_on:
   - diat-qa-db
volumes:
 code-qa:
 database:
networks:
 diat_qa_net:
  driver: bridge
  ipam:
   driver: default
   config:
    -
     subnet: 174.25.100.0/24
